name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [main]
    push:
        branches:
            - main
    workflow_dispatch:


permissions:
    pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest ]  # , windows-latest, macos-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17
                    architecture: x64
            -   name: Cache Maven packages
                uses: actions/cache@v4.0.0
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2-
            -   name: Build with Maven
                run: mvn --no-transfer-progress -DskipTests -Dmaven.test.skip=true verify 

            -   name: List Target Directories
                run: |
                    find . -type d -name "target" | grep -v "/\." | sed 's|^./||'
            -   name: List Source Directories
                run: |
                    find . -type d -name "src" | grep -v "/\." | sed 's|^./||'

            -   name: Run SpotBugs
                run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs
            
            -   name: Archive production artifacts
                uses: actions/upload-artifact@v3
                with:
                  name: spotbugs-xml
                  path: |
                    target/spotbugsXml.xml

            -   name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
                with:
                    args: 
                        -Dsonar.projectKey=${{ secrets.WEBGOAT_SONAR_PROJECT_KEY }}  
                        -Dsonar.java.binaries=./target





            -   name: Run SpotBugs
                run: |
                    wget -qO- https://github.com/spotbugs/spotbugs/releases/download/4.8.3/spotbugs-4.8.3.tgz | tar -xz
                    ls
                    chmod 700 spotbugs-4.8.3/bin/spotbugs
                    ./spotbugs-4.8.3/bin/spotbugs -textui -xml -output spotbugs_report.xml target
                #   java -jar spotbugs-4.8.3/spotbugs-4.8.3.tar -textui -xml -output spotbugs_report.xml gdx-ai/target
                #   mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs
        
            -   name: Archive production artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: spotbugs-xml
                    path: |
                        spotbugs_report.xml


            -   name: Run PMD
                id: pmd
                uses: pmd/pmd-github-action@v2
                with:
                  rulesets: 'rulesets/java/quickstart.xml'
                  analyzeModifiedFilesOnly: false
            -   name: Upload SARIF file
                uses: github/codeql-action/upload-sarif@v3
                with:
                  sarif_file: pmd-report.sarif